# Generated by Django 3.0.2 on 2020-01-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('priceSmall', models.FloatField(blank=True)),
                ('priceLarge', models.FloatField()),
            ],
        ),
    ]
