# Generated by Django 3.0.2 on 2020-01-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='priceLarge',
            field=models.FloatField(default=7.95),
        ),
        migrations.AlterField(
            model_name='sub',
            name='priceSmall',
            field=models.FloatField(blank=True, default=6.5, null=True),
        ),
    ]
