# Generated by Django 3.0.2 on 2020-01-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200118_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizeLarge',
            field=models.BooleanField(default=True),
        ),
    ]
