# Generated by Django 3.0.2 on 2020-01-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='topping',
        ),
        migrations.AddField(
            model_name='product',
            name='topping',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
