# Generated by Django 3.0.2 on 2020-01-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200118_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dinner_plt',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pizza_normal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pizza_siz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='salad',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizeLarge',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='product',
            name='topping',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('L', 'LARGE'), ('S', 'SMALL'), ('SING', 'SINGLE')], default=0, max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default=0, max_length=64),
        ),
        migrations.AlterField(
            model_name='salad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
