# Generated by Django 3.0.2 on 2020-01-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_order_total_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
