# Generated by Django 3.0.2 on 2020-01-19 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_delete_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
