# Generated by Django 3.0.2 on 2020-01-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_delete_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DinnerPlatter',
        ),
        migrations.DeleteModel(
            name='Pasta',
        ),
        migrations.DeleteModel(
            name='PizzaType',
        ),
        migrations.DeleteModel(
            name='Salad',
        ),
        migrations.DeleteModel(
            name='SicilianPizzaType',
        ),
        migrations.DeleteModel(
            name='Sub',
        ),
    ]
