# Generated by Django 3.0.2 on 2020-01-22 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_completedorders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompletedOrders',
            new_name='CompletedOrder',
        ),
    ]
