# Generated by Django 3.0.2 on 2020-01-23 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20200122_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='toppingchoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Topping'),
        ),
    ]
