# Generated by Django 3.0.2 on 2020-01-24 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_order_toppingchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TpgChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.ManyToManyField(to='orders.Topping')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='toppingchoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.TpgChoice'),
        ),
    ]
