# Generated by Django 3.0.2 on 2020-01-24 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_tpgchoice_ordernumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpgchoice',
            name='topping',
        ),
        migrations.AddField(
            model_name='tpgchoice',
            name='topping',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.Topping'),
        ),
    ]
