# Generated by Django 3.0.2 on 2020-01-24 20:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20200124_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='tpgchoice',
            name='multiple',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bacon', 'Bacon'), ('Mushroom', 'Mushroom'), ('Ham', 'Ham')], max_length=18, null=True),
        ),
    ]
