# Generated by Django 3.0.2 on 2020-01-24 20:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_tpgchoice_multiple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tpgchoice',
            name='multiple',
        ),
        migrations.AlterField(
            model_name='tpgchoice',
            name='topping',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sausage', 'Sausage'), ('Mushrooms', 'Mushrooms'), ('Onions', 'Onions'), ('Ham', 'Ham'), ('Canadian Bacon', 'Canadian Bacon'), ('Spinach', 'Spinach'), ('Tomato & Basil', 'Tomato & Basil'), ('Green Pepper', 'Green Pepper'), ('Anchovies', 'Anchovies'), ('Artichoke', 'Artichoke'), ('Buffalo Chicken', 'Buffalo Chicken'), ('Eggplant', 'Eggplant'), ('Zucchini', 'Zucchini'), ('Fresh Garlic', 'Fresh Garlic')], max_length=146, null=True),
        ),
    ]
